id: Blueprint.DukesBankApplicationForvSphere
name: Dukes Bank Application For vSphere
description: Three-tier Dukes Bank application on Linux nodes for vSphere; Apache HTTP Server for load balancer, JBoss Server for application server, and MySQL Server for database server. This is the basic version of Dukes Bank on Linux nodes.
status: PUBLISHED
properties:
  __nsx.management_endpoint_name:
    fixed: vCenter
    secured: false
    visible: false
  __nsx.transport_zone_name:
    fixed: NSXTransport
    secured: false
    visible: false
components:
  ApacheLB_1:
    type: Software.ApacheLB
    dependsOn:
    - DukesBankApp_1
    - centos_yum_repo_1
    data:
      JAVA_HOME:
        default: /opt/vmware-jre
        required: true
      ajp_proxy_context: {}
      appsrv_routes:
        fixed: ${_resource~JBossAppServer_1~JVM_ROUTE}
        required: true
      autogen_sticky_cookie: 'NO'
      config_httpd_conf:
        fixed: /etc/httpd/conf/httpd.conf
      config_static_site:
        fixed: /var/www/html
      host: ${_resource~loadbalancer-node}
      http_node_ips:
        fixed: ${_resource~appserver-node~ip_address}
        required: true
      http_node_port:
        fixed: ${_resource~JBossAppServer_1~JBOSS_PORT_NUMBER}
        required: true
      http_port: '8081'
      http_proxy_port:
        default: '80'
        required: true
      httpd_dir:
        fixed: /etc/httpd
      service_restart:
        fixed: service httpd restart
      service_start:
        fixed: service httpd start
      service_stop:
        fixed: service httpd stop
      tomcat_context: {}
      use_ajp:
        default: 'NO'
        required: true
  App:
    type: Infrastructure.Network.Network.NSX.OnDemand.Routed
    data:
      dns:
        fixed:
          dns_search_suffix: inkysea.com,inkysea.local
          dns_suffix: inkysea.com
          primary_dns: 10.25.27.1
      name:
        fixed: App
      parent_network_profile:
        fixed: NSX Routed
  DB:
    type: Infrastructure.Network.Network.NSX.OnDemand.Routed
    data:
      dns:
        fixed:
          dns_search_suffix: inkysea.com,inkysea.local
          dns_suffix: inkysea.com
          primary_dns: 10.25.27.1
      name:
        fixed: DB
      parent_network_profile:
        fixed: NSX Routed
  DukesBankApp_1:
    type: Software.DukesBankApp
    dependsOn:
    - DukesBankDBSetup_1
    data:
      APPD_SCRIPT: ''
      EAR_FILE: https://$app_content_server_ip:$app_content_server_port/artifacts/blueprint/dukesbank/dukesbank-2b.ear
      JAR_FILE: https://$app_content_server_ip:$app_content_server_port/artifacts/blueprint/dukesbank/mysql.jdbc-5.1.6.jar
      JAVA_HOME:
        fixed: ${JBossAppServer_1~JAVA_HOME}
      JBOSS_DATASOURCE_TEMPLATE: https://$app_content_server_ip:$app_content_server_port/artifacts/blueprint/dukesbank/jboss-ds.xml.tmpl
      app_content_server_ip:
        default: vra-app-1.inkysea.com
        required: true
        visible: true
      app_content_server_port:
        default: '5480'
        required: true
        visible: true
      db_host:
        fixed: ${_resource~database-node~ip_address}
      db_password:
        fixed: ${DukesBankDBSetup_1~db_password}
      db_port:
        fixed: ${MySql_1~db_port}
      db_user:
        fixed: ${DukesBankDBSetup_1~db_username}
      dukes_db:
        fixed: ${DukesBankDBSetup_1~db_name}
      host: ${_resource~JBossAppServer_1}
      jboss_deploy_component_script: https://$app_content_server_ip:$app_content_server_port/artifacts/blueprint/dukesbank/deploy_component.sh
      jboss_deploy_datasource_script: https://$app_content_server_ip:$app_content_server_port/artifacts/blueprint/dukesbank/deploy_datasource.sh
  DukesBankDBSetup_1:
    type: Software.DukesBankDBSetup
    data:
      db_name:
        default: dukes_db
        required: true
      db_password:
        default: ''
        required: true
        secured: true
      db_username:
        default: dukes_admin
        required: true
      host: ${_resource~MySql_1}
      init_db_password:
        default: ''
        required: true
        secured: true
      init_db_username:
        default: root
        required: true
  JBossAppServer_1:
    type: Software.JBossAppServer
    dependsOn:
    - centos_yum_repo_2
    data:
      Install_Path: ''
      JAVA_HOME:
        default: /opt/vmware-jre
        required: true
      JBOSS_BOOTRC_TEMPLATE: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/boot.rc.tmpl
      JBOSS_INSTANCE_NAME: default
      JBOSS_JMX_CONSOLE_USERS_TEMPLATE: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/jmx-console-users.properties.tmpl
      JBOSS_JMX_PWD:
        default: ''
        secured: true
      JBOSS_JMX_USER: admin
      JBOSS_NAME_AND_VERSION: jboss-5.1.0.GA
      JBOSS_PORT_NUMBER:
        default: '8080'
        required: true
      JVM_ROUTE: '0'
      app_content_server_ip:
        default: vra-app-1.inkysea.com
        required: true
        visible: true
      app_content_server_port:
        default: '5480'
        required: true
        visible: true
      cheetah_install_script: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/cheetah_install.sh
      cheetah_tgz_url: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/cheetah-2.4.4.tar.gz
      host: ${_resource~appserver-node}
      jboss_configure_script: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/configure.sh
      jboss_install_script: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/install.sh
      zip_url: https://$app_content_server_ip:$app_content_server_port/artifacts/software/jboss/jboss-5.1.0.GA.zip
  LB:
    type: Infrastructure.Network.Network.NSX.OnDemand.Routed
    data:
      dns:
        fixed:
          dns_search_suffix: inkysea.com,inkysea.local
          dns_suffix: inkysea.com
          primary_dns: 10.25.27.1
      name:
        fixed: LB
      parent_network_profile:
        fixed: NSX Routed
  MySql_1:
    type: Software.MySql
    dependsOn:
    - centos_yum_repo_3
    data:
      JAVA_HOME:
        default: /opt/vmware-jre
        required: true
      db_port:
        default: '3306'
        required: true
      db_root_password:
        default: ''
        required: true
        secured: true
      db_root_username:
        default: root
        required: true
      global_ftp_proxy: {}
      global_http_proxy: {}
      global_https_proxy: {}
      host: ${_resource~database-node}
  NSXLB:
    type: Infrastructure.Network.LoadBalancer.NSX.OnDemand
    data:
      name:
        fixed: NSXLB
      services:
        fixed:
        - health_check_interval: 5
          health_threshold: 5
          id: HTTP
          isSelected: true
          name: HTTP
          port: 80
          response_timeout: 5
          service_URI: ''
          unhealth_threshold: 10
        - health_check_interval: 5
          health_threshold: 5
          id: HTTPS
          isSelected: true
          name: HTTPS
          port: 443
          response_timeout: 5
          service_URI: ''
          unhealth_threshold: 10
      tier:
        fixed: ${_resource~loadbalancer-node}
      tier_nic_index:
        fixed: 0
      vip_network:
        fixed: ${_resource~Web}
  Web:
    type: Infrastructure.Network.Network.NSX.OnDemand.Routed
    data:
      dns:
        fixed:
          dns_search_suffix: inkysea.com,inkysea.local
          dns_suffix: inkysea.com
          primary_dns: 10.25.27.1
      name:
        fixed: Web
      parent_network_profile:
        fixed: NSX Routed
  appserver-node:
    type: Infrastructure.CatalogItem.Machine.Virtual.vSphere
    data:
      _cluster:
        default: 1
        max: 10
        min: 1
      action:
        fixed: LinkedClone
      allow_storage_policies:
        fixed: false
      blueprint_type:
        fixed: '0'
      cpu:
        default: 1
        max: 1
        min: 1
      disks:
      - capacity: 80
        custom_properties: null
        id: 1458086762968
        initial_location: ''
        is_clone: true
        label: Hard disk 1
        storage_reservation_policy: ''
        userCreated: false
        volumeId: 0
      display_location:
        fixed: false
      guest_customization_specification: Linux
      machine_actions:
        default: ''
        required: false
        secured: false
        visible: false
      max_network_adapters: {}
      max_volumes: {}
      memory:
        default: 1024
        max: 2048
        min: 1024
      nics:
      - address: ''
        assignment_type: Static
        id: 0
        load_balancing: ''
        network: ${_resource~App}
        network_profile: NSX Routed
      osfamily:
        default: LINUX
        required: false
        secured: false
        visible: false
      property_groups: {}
      provisioning_workflow:
        fixed:
          id: CloneWorkflow
          label: CloneWorkflow
      security_groups: []
      security_tags: []
      source_machine:
        fixed:
          id: 390406ac-457d-420f-8df8-a6077e63125f
          label: centos7_vra
      source_machine_external_snapshot:
        fixed: 1
      source_machine_name:
        fixed: centos7_vra
      source_machine_vmsnapshot:
        fixed:
          id: '9'
      storage:
        default: 80
        max: 80
        min: 80
  centos_yum_repo_1:
    type: Software.centosyumrepo
    data:
      host:
        fixed: ${_resource~loadbalancer-node}
      repoURL: https\:\/\/vra-app-1\.inkysea\.com\/artifactory\/list/
  centos_yum_repo_2:
    type: Software.centosyumrepo
    data:
      host:
        fixed: ${_resource~appserver-node}
      repoURL: https\:\/\/vra-app-1\.inkysea\.com\/artifactory\/list/
  centos_yum_repo_3:
    type: Software.centosyumrepo
    data:
      host:
        fixed: ${_resource~database-node}
      repoURL: https\:\/\/vra-app-1\.inkysea\.com\/artifactory\/list/
  database-node:
    type: Infrastructure.CatalogItem.Machine.Virtual.vSphere
    data:
      _cluster:
        default: 1
        max: 1
        min: 1
      action:
        fixed: LinkedClone
      allow_storage_policies:
        fixed: false
      blueprint_type:
        fixed: '0'
      cpu:
        default: 1
        max: 1
        min: 1
      description: DB for Dukes Bank application
      disks:
      - capacity: 80
        custom_properties: null
        id: 1458086797683
        initial_location: ''
        is_clone: true
        label: Hard disk 1
        storage_reservation_policy: ''
        userCreated: false
        volumeId: 0
      display_location:
        fixed: false
      guest_customization_specification: Linux
      machine_actions:
        default: ''
        required: false
        secured: false
        visible: false
      max_network_adapters: {}
      max_volumes: {}
      memory:
        default: 512
        max: 2048
        min: 512
      nics:
      - address: ''
        assignment_type: Static
        id: 0
        load_balancing: ''
        network: ${_resource~DB}
        network_profile: NSX Routed
      osfamily:
        default: LINUX
        required: false
        secured: false
        visible: false
      property_groups: {}
      provisioning_workflow:
        fixed:
          id: CloneWorkflow
          label: CloneWorkflow
      security_groups: []
      security_tags: []
      source_machine:
        fixed:
          id: 390406ac-457d-420f-8df8-a6077e63125f
          label: centos7_vra
      source_machine_external_snapshot:
        fixed: 1
      source_machine_name:
        fixed: centos7_vra
      source_machine_vmsnapshot:
        fixed:
          id: '9'
      storage:
        default: 80
        max: 80
        min: 80
  loadbalancer-node:
    type: Infrastructure.CatalogItem.Machine.Virtual.vSphere
    data:
      _cluster:
        default: 1
        max: 1
        min: 1
      action:
        fixed: LinkedClone
      allow_storage_policies:
        fixed: false
      blueprint_type:
        fixed: '0'
      cpu:
        default: 1
        max: 1
        min: 1
      disks:
      - capacity: 80
        custom_properties: null
        id: 1458086735614
        initial_location: ''
        is_clone: true
        label: Hard disk 1
        storage_reservation_policy: ''
        userCreated: false
        volumeId: 0
      display_location:
        fixed: false
      guest_customization_specification: Linux
      machine_actions:
        default: ''
        required: false
        secured: false
        visible: false
      max_network_adapters: {}
      max_volumes: {}
      memory:
        default: 256
        max: 2048
        min: 256
      nics:
      - address: ''
        assignment_type: Static
        id: 0
        load_balancing: HTTP,HTTPS
        network: ${_resource~Web}
        network_profile: NSX Routed
      osfamily:
        default: LINUX
        required: false
        secured: false
        visible: false
      property_groups: {}
      provisioning_workflow:
        fixed:
          id: CloneWorkflow
          label: CloneWorkflow
      security_groups: []
      security_tags: []
      source_machine:
        fixed:
          id: 390406ac-457d-420f-8df8-a6077e63125f
          label: centos7_vra
      source_machine_external_snapshot:
        fixed: 1
      source_machine_name:
        fixed: centos7_vra
      source_machine_vmsnapshot:
        fixed:
          id: '9'
      storage:
        default: 80
        max: 80
        min: 80
layout:
  ApacheLB_1: 0,0
  App: 2,0
  DB: 3,0
  DukesBankApp_1: 0,0
  DukesBankDBSetup_1: 0,0
  JBossAppServer_1: 0,0
  LB: 4,0
  MySql_1: 0,0
  NSXLB: 0,0
  Web: 1,0
  appserver-node: 0,2
  centos_yum_repo_1: 1,0
  centos_yum_repo_2: 1,0
  centos_yum_repo_3: 1,0
  database-node: 0,3
  loadbalancer-node: 0,1
